INSERT INTO COUNTRY (ID,NAME,NATIONALITY,CODE, DELETED) VALUES (1,'Argentina','Argentina','AR', 0);
INSERT INTO COUNTRY (ID,NAME,NATIONALITY,CODE, DELETED) VALUES (2,'Chile','Chilena','CL', 0);

INSERT INTO PERSON (ID,ALL_NAMES,SURNAMES,COUNTRY_ID,BIRTHDAY,DELETED) VALUES (1,'Nicolas Matias','Pfleger Schwarz', 1,'1987-05-16',0)